/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e8e1d9',
        'primary': '#9a401c',
        'tertiary-container': '#837165',
        'on-secondary-fixed': '#111f08',
        'tertiary-fixed': '#f5ded0',
        'surface-bright': '#fff8f1',
        'outline-variant': '#dcc1b8',
        'on-secondary-container': '#58694c',
        'inverse-surface': '#33302a',
        'surface': '#fff8f1',
        'inverse-primary': '#ffb59b',
        'on-primary-fixed-variant': '#7e2c08',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f7f0e7',
        'primary-fixed': '#ffdbcf',
        'secondary-container': '#d5e9c4',
        'secondary-fixed': '#d5e9c4',
        'primary-container': '#ba5832',
        'error-container': '#ffdad6',
        'surface-container': '#f4ede4',
        'on-secondary-fixed-variant': '#3b4b30',
        'surface-dim': '#e0d9d0',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'background': '#fff8f1',
        'outline': '#89726a',
        'secondary': '#536346',
        'surface-tint': '#9e421e',
        'surface-container-high': '#eee7de',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#534439',
        'secondary-fixed-dim': '#bacda9',
        'tertiary-fixed-dim': '#d8c2b5',
        'surface-variant': '#e8e1d9',
        'primary-fixed-dim': '#ffb59b',
        'on-error': '#ffffff',
        'surface-container-low': '#faf3e9',
        'on-background': '#1e1b16',
        'on-tertiary': '#ffffff',
        'tertiary': '#69594e',
        'on-secondary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#380d00',
        'on-surface': '#1e1b16',
        'on-surface-variant': '#56423c',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#251911',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-lg': '1.5rem',
        'gutter': '1.5rem',
        'space-md': '1rem',
        'margin-mobile': '1.25rem',
        'margin': '3rem',
        'space-sm': '0.5rem',
        'gutter-mobile': '1rem',
        'margin-tablet': '2rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        'headline-xl-mobile': ['Playfair Display'],
        'body-md': ['Plus Jakarta Sans'],
        'title-md': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans'],
        'display-lg-mobile': ['Playfair Display'],
        'headline-lg': ['Playfair Display'],
        'headline-xl': ['Playfair Display'],
        'label-sm': ['Plus Jakarta Sans'],
        'headline-md': ['Playfair Display'],
        'display-lg': ['Playfair Display'],
        'body-lg': ['Plus Jakarta Sans'],
        'headline-sm': ['Playfair Display'],
        'label-lg': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-xl-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-md': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg-mobile': ['38px', { lineHeight: '46px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.04em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
